version: "3.9"
services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:3000 manage:app
    image: web_prod:latest
    expose:
      - 3000
    env_file:
      - ./.env.prod
    depends_on:
      - postgis
  postgis:
    env_file:
      - database.prod.conf
    image: postgis/postgis
    restart: on-failure
    ports:
      - "1447:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
  nginx:
    build: ./services/nginx
    ports:
      - "1444:80"
    depends_on:
      - web
volumes:
  pg_data: