version: "3.9"
services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    image: web:latest
    ports:
      - "3000:5000"
    volumes:
      - ./services/web/:/usr/src/app/
    env_file:
      - ./.env.dev
  postgis:
    env_file:
      - database.conf
    image: postgis/postgis
    restart: on-failure
    ports:
      - "3333:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
volumes:
  pg_data: